package com.everis.practicacloudcompra.model;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 25/09/2019 04:27:59 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "inventario", catalog = "practica3")
public class Inventario implements java.io.Serializable {

	private int id;
	private String nombre;
	private Integer stock;
	@JsonIgnore
	private Set<Compra> compras = new HashSet<Compra>(0);

	public Inventario() {
	}

	public Inventario(int id) {
		this.id = id;
	}

	public Inventario(int id, String nombre, Integer stock, Set<Compra> compras) {
		this.id = id;
		this.nombre = nombre;
		this.stock = stock;
		this.compras = compras;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "stock")
	public Integer getStock() {
		return this.stock;
	}

	public void setStock(Integer stock) {
		this.stock = stock;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inventario")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

}
